CREATE_TIME_STAMP = 'DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'.freeze
APDATE_TIME_STAMP = 'DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP'.freeze
DEFAULT_DATETIME = '9999-12-31 23:59:59'.freeze
DEFAULT_DATE = '9999-12-31'.freeze
SEXES = { "未登録": 0, "男": 1, "女": 2, "無回答": 3 }.freeze
